### PR TITLE
Update Spanish (Spain).csv

### PR DESCRIPTION
**Pull request by angel-ag2**

### CODE REVIEW

**Comment by abstractspoon** [comment]
Looks good to me Peter.

However you raise a good point, we probably need to give more guidance so that it's clear that the 'English' MUST NOT BE CHANGED.

However (again) we can always roll back changes that alter the English accidentally or otherwise.

**Comment by abstractspoon** [comment]
I've added you as a collaborator angelTDL. Welcome aboard!

**Comment by Pierre-de-la-Verre** [comment]
Hi Dan

I meant that "About..."   should be „"Acerca de... and not "Acerca de"

Same with "All Files (_._)" – now it is "todos los ficheros" instead of "todos los ficheros (_._)"        

Peter

Von: .dan.g. [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. Juli 2015 12:47
An: abstractspoon/ToDoList_Resources
Betreff: Re: [ToDoList_Resources] Update Spanish (Spain).csv (#15)

Looks good to me Peter.

However you raise a good point, we probably need to give more guidance so that it's clear that the 'English' MUST NOT BE CHANGED.

However (again) we can always roll back changes that alter the English accidentally or otherwise.

**Comment by abstractspoon** [comment]
I apologise Peter, you are quite right. I didn't look closely enough.

I have reverted the change and angelTDL's status until he resubmits the changes.

**Comment by WM-QUIT** [comment]
Peter, can I make you responsible for overseeing all changes to translations? 

That way I won't make this mistake again!

**Comment by Pierre-de-la-Verre** [comment]
Yes, I will see what I can do (and if I understand the features of Github)

Peter

Von: WM-QUIT [mailto:notifications@github.com] 
Gesendet: Dienstag, 28. Juli 2015 13:21
An: abstractspoon/ToDoList_Resources
Cc: Peter Glasl
Betreff: Re: [ToDoList_Resources] Update Spanish (Spain).csv (#15)

Can I make you responsible for overseeing all changes to translations? That
way I won't make this mistake again!

**Comment by abstractspoon** [comment]
Thx Peter. And remember I am always available for consultation at very agreeable rates!

ps. The actual release of 7.0 is probably at least a week away so no need to stress.

**Comment by Pierre-de-la-Verre** [comment]
Hi angelTDL
what's the current state with the language file? is it locally checked on your PC and ready to be merge to the main file?

Regards

Peter

**Comment by angel-ag2** [comment]
Hi Peter. yes I worked from the PC and have copied to github.

**Comment by Pierre-de-la-Verre** [comment]
```
> have copied to github. 
```

To your branch or to the main-file?

**Comment by angel-ag2** [comment]
In main-file? f you do not show what I can send attached?

**Comment by Pierre-de-la-Verre** [comment]
```
> f you do not show what I can send attached?
```

I don't understand exactly what you mean, but I asked if you copied your modifications 
- to your branch of abstractspoon (which has to be merged to the main file by a collaborator)
  or
- if you have the rights of a collaborator and modified the mainfile by yourself.

**Comment by angel-ag2** [comment]
yesterday I included the last translations in the main branch but when I enter again I do not see them. what am I doing wrong? thx

**Comment by Pierre-de-la-Verre** [comment]
I don't know. It seems that I don't understand Github enough.

The latest modification of Spanish.csv in main-file was 14 days ago:
https://github.com/abstractspoon/ToDoList_Resources/commits/master/Translations/Spanish%20%28Spain%29.csv

**Comment by angel-ag2** [comment]
and how can we fix it? As I can send cvs file attachment?

**Comment by Pierre-de-la-Verre** [comment]
Yes.
Please check it for current RC5 and then send the file to me: nojunk217           hotmail      com

**Comment by Pierre-de-la-Verre** [comment]
Hi angel

please consider the current discussion here: "new formatted strings"
http://www.codeproject.com/Messages/5106273/Modified-strings.aspx

**Comment by angel-ag2** [comment]
done.

thx

**Comment by Pierre-de-la-Verre** [comment]
The „Clean up / Limpiar“ shows these strings need translation:

"- unnamed -"    ""           "text"
"Small Icons"      ""           "menu.59408"
"Source Control Change(s)"         ""           "text"
"Spreadsheet Files (*.csv)"           ""           "combobox.1136"
"Steps"  ""           "groupbox"
"Subtasks are indented at each level with"            ""           "label.1000"
"Table..."            ""           "menu.32799"
"Task Dialog"     ""           "menu"
"\n-nt <title>\tCreates a new task in the active tasklist with the specified title\n-pid <id>\tSpecifies the parent task in which to create the new task\n-bid <id>\tSpecifies the sibling task after which to create the new task\n-tid <id>\tSelects the task in the active tasklist\n-cm <comments>\tAdds to the 'Comments' for the currently selected task\n-tv <version>\tSets the 'Version' for the currently selected task\n-xid <ext_id>\tSets the 'external ID' for the currently selected task\n-c <categories>\tSets the 'Category(s) for the currently selected task\n-at <alloc to>\tSets the 'Allocated To(s)' for the currently selected task"    ""           "text"

The long, last string in nearly the same as the existing – only the „-cm ... section“ has some words changed.
tdl_tooltip_german

The new strings with „:\t“ could be optimized (more or less \t; shorter words) to get a real formatted table:

I sent the Gif to Dan to add it.

Thanks

Peter

**Comment by angel-ag2** [comment]
done, please refer angelTDL translation: patch-2 (6 minutes ago)

**Comment by angel-ag2** [comment]
Please, and what Dan mail?

**Comment by Pierre-de-la-Verre** [comment]
I'm confused - the current file has still the missing strings and the unfine formatting of the tooltips ..???

tdl_spanish

**Comment by angel-ag2** [comment]
Please, and what Dan mail? and
the file with which I worked was generated by todolist using the "Enabled 'Add-to-Dictionary' option for translator. Maybe this is what is confusing you? :)

**Comment by Pierre-de-la-Verre** [comment]
```
           > Please, and what Dan mail?
```

Nothing. I just sent him your new Spanish Flag.

```
        > Maybe this is what is confusing you?
```

Have you also used the „clean up / limpiar“ command?

Have you checked the appearance of the tooltip?

Last week I made a 27 min – video which describes all the translating stuff:

http://autode.sk/1E2rAyu 

If you are not sure about all small tricks with the translation you are invited to take a look. Please let me know if it is / was helpful for you.

Peter

Von: angel (Ag2) [mailto:notifications@github.com] 
Gesendet: Mittwoch, 12. August 2015 14:28
An: abstractspoon/ToDoList_Resources
Cc: Peter Glasl
Betreff: Re: [ToDoList_Resources] Update Spanish (Spain).csv (#15)

Please, and what Dan mail? and
the file with which I worked was generated by todolist using the "Enabled 'Add-to-Dictionary' option for translator. Maybe this is what is confusing you? :)

**Comment by angel-ag2** [comment]
HI, thanks for sending mail and checked many of the descriptions and change enough. You ever seen that was not translated correctly?

**Comment by Pierre-de-la-Verre** [comment]
Hi Angel

```
> You ever seen that was not translated correctly?
```

Only a little bit - I mentioned it yesterday ("21 hours ago")

**Comment by angel-ag2** [comment]
Hi, forgive but to which you refer?

**Comment by mlocati** [comment]
Hi @angelTDL 

If you're still interested in translating ToDoList, I just set up a new system to translate it.
Please remark that's not officially supported by the ToDoList developers, but I used it to translate TDL to Italian and I find it so useful that I think any translators should use it.

If you are interested in giving it a try, here's what you can do:
1. [create a free account](https://www.transifex.com/signup/) on the Transifex (it's an online collaborative platform used by many small and big organizations to translate)
2. Go to the [ToDoList](https://www.transifex.com/mlocati/todolist/) project on Transifex and click the green `Join team` button
3. Once you've done it, I'll accept your request and you'll be able to start translating ToDoList in a much easier way.
4. When you finished translating on Transifex, please [drop me a message](https://www.transifex.com/user/messages/compose/mlocati/): I'll create a pull request on GitHub with your translations (if you prefer I can explain you how to do this step, but it's a bit techy)

**Pull request merged**
