### PR TITLE
Updated Slovenian translation 

### PR DESCRIPTION
**Pull request by JadranR**
Translation per date 18.08.2020 for version 8.0.0. Beta.
Best Regards,
Jadran

### CODE REVIEW

**Comment by JadranR** [comment]
Update Slovenian translation for ToDoList, per Date 23.05.2022
[Slovenian (Slovenia).zip](https://github.com/abstractspoon/ToDoList_Resources/files/8753827/Slovenian.Slovenia.zip)
Best Regards,
Jadran Rudec

**Comment by Pierre-de-la-Verre** [comment]
Hi Jadran

thansk a lot. There are a fex new strings in Github, added 2 days ago. Could you translate them too before I upload your file?

Regards
Peter
________________________________
Von: Jadran ***@***.***>
Gesendet: Montag, 23. Mai 2022 10:39
An: abstractspoon/ToDoList_Resources ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: Re: [abstractspoon/ToDoList_Resources] Updated Slovenian translation (PR #124)


Update Slovenian translation for ToDoList, per Date 23.05.2022
Slovenian (Slovenia).zip<https://github.com/abstractspoon/ToDoList_Resources/files/8753827/Slovenian.Slovenia.zip>
Best Regards,
Jadran Rudec

**Comment by JadranR** [comment]
Hi,

Slovenian translation is completed.

Kind Regards,
Jadran

V V tor., 24. maj 2022 ob 12:25 je oseba Pierre-de-la-Verre <
***@***.***> napisala:

**Comment by abstractspoon** [comment]
Hi Jadran

I'm sorry to report that we can't use your updated translation because it seems to have been based on a version of the Slovenian translation that is very out of date (maybe your original) making the merge process extremely difficult.

I suspect that this is partly my fault because I do a lot of editing of the translation files when I need to make fixes or change the text/format. I don't change the translated part but I do make quite a lot of changes to the English. 

What this means is that translators must always get the latest version from GitHub (or at the very least the latest released version of the translations) before making their new changes. Probably the best way to prevent these sorts of problems would be to [edit the file directly in GitHub](https://github.com/abstractspoon/ToDoList_Resources/edit/master/Translations/Slovenian%20(Slovenia).csv).

Once again I apologise for not being able to accept your pull request.

Regards

Dan

**Comment by JadranR** [comment]
Hi Dan,

Thank you for the explanation. The Slovenian translation I sent by e-mail
is the result of a comparison with the English file of the latest version
of the application, and I have invested quite a bit of time in this work. The
comparison took place line by line. Following your notice, I went to GitHub
and translated untranslated strings there. I didn’t watch the content on
GitHub and I didn’t compare it to my last translation. No panic. As I will
not be present for the next 3 weeks (I will be in Slovenia and not in
Germany), I will not be translating any applications during this time. Your
app will be as it is for a while. With respect,


V V ned., 29. maj 2022 ob 06:19 je oseba .dan.g. ***@***.***>
napisala:

**Comment by Pierre-de-la-Verre** [comment]
_I have invested quite a bit of time in this work. The comparison took place line by line_

Do you use TDLTransEdit.exe, usually stored in c:\Program Files (x86)\Todolist\? I think you don't need to compare line by line and so on ..

**Comment by JadranR** [comment]
Hi, Dan

Thanks for the information. So far I haven’t known about it and haven’t
used it either. I use the WinMerge application to compare files.

I'm wondering if you can send me the latest version (Beta) of the English
language file for comparison with my translation because I'm not a
masochist. I don't know which version of the Slovenian translation is on
GitHub and I won't deal with it.

With respect,

Jadran Rudec

V V ned., 29. maj 2022 ob 23:27 je oseba Pierre-de-la-Verre <
***@***.***> napisala:

**Comment by abstractspoon** [comment]
Hi Jadran

I've sent the latest version of 'YourLanguage.csv' to the email address  from which I received your original translation.

Regards

Dan

**Comment by JadranR** [comment]
Great, thanks for letting me know.

V pon., 30. maj 2022 08:28 je oseba .dan.g. ***@***.***>
napisala:

**Pull request closed without merging**
