### PR TITLE
Update Russian (Russia).csv

### PR DESCRIPTION
**Pull request by mugrrrr**

### CODE REVIEW

**Comment by Pierre-de-la-Verre** [comment]
Hi Alex

is it possible that you check and refine the translation also on your PC? That would be great :-)

**Comment by mugrrrr** [comment]
Yes, I have it in my plans.

**Comment by Pierre-de-la-Verre** [comment]
Hi mugrrrr
what's the current state with the language file? is it locally checked on your PC and ready to be merge to the main file?

Regards

Peter

**Comment by Pierre-de-la-Verre** [comment]
Hi mugrrrr

please consider the current discussion here: "new formatted strings"
http://www.codeproject.com/Messages/5106273/Modified-strings.aspx

Edit:
Please check if the tooltip, created by the new strings, makes a well formatted table - use more or less \t or longer / shorter words:
tdl_tooltip_german

**Comment by mugrrrr** [comment]
Hi Peter
Currently don't have enough time for it, it will be updated as soon as it's ready.

**Comment by Pierre-de-la-Verre** [comment]
Hi Mugrrrr

the release of TDL 7 is planned for this Saturday. Any change to upload a finished or improved language file?

Peter

Von: mugrrrr [mailto:notifications@github.com] 
Gesendet: Mittwoch, 12. August 2015 16:49
An: abstractspoon/ToDoList_Resources
Cc: Peter Glasl
Betreff: Re: [ToDoList_Resources] Update Russian (Russia).csv (#18)

Hi Peter
Currently don't have enough time for it, it will be updated as soon as it's ready.

**Comment by mugrrrr** [comment]
I'll update it as soon as it's ready locally, as github editing seems not friendly to me.

**Comment by Pierre-de-la-Verre** [comment]
If it helps – here is 
- the current file, downloaded from Github, and „Cleaned up“
- the file with the removed strings, which can partially(!!!) help to translate the missing strings (50 different lines + 50 nearly the same lines)

Peter

Von: mugrrrr [mailto:notifications@github.com] 
Gesendet: Donnerstag, 13. August 2015 10:26
An: abstractspoon/ToDoList_Resources
Cc: Peter Glasl
Betreff: Re: [ToDoList_Resources] Update Russian (Russia).csv (#18)

I'll update it as soon as it's ready locally, as github editing seems not friendly to me.

**Comment by Pierre-de-la-Verre** [comment]
## I mean this:

The „Clean up / Limpiar“ shows these strings need translation:

"- unnamed -"    ""           "text"
"Small Icons"      ""           "menu.59408"
"Source Control Change(s)"         ""           "text"
"Spreadsheet Files (*.csv)"           ""           "combobox.1136"
"Steps"  ""           "groupbox"
"Subtasks are indented at each level with"            ""           "label.1000"
"Table..."            ""           "menu.32799"
"Task Dialog"     ""           "menu"
"\n-nt <title>\tCreates a new task in the active tasklist with the specified title\n-pid <id>\tSpecifies the parent task in which to create the new task\n-bid <id>\tSpecifies the sibling task after which to create the new task\n-tid <id>\tSelects the task in the active tasklist\n-cm <comments>\tAdds to the 'Comments' for the currently selected task\n-tv <version>\tSets the 'Version' for the currently selected task\n-xid <ext_id>\tSets the 'external ID' for the currently selected task\n-c <categories>\tSets the 'Category(s) for the currently selected task\n-at <alloc to>\tSets the 'Allocated To(s)' for the currently selected task"    ""           "text"

The long, last string in nearly the same as the existing – only the „-cm ... section“ has some words changed.
tdl_tooltip_german

The new strings with „:\t“ could be optimized (more or less \t; shorter words) to get a real formatted table:

**Comment by Pierre-de-la-Verre** [comment]
Solved for TDL 7.0 via E-Mail

**Comment by mlocati** [comment]
Hi @mugrrrr 

If you're still interested in translating ToDoList, I just set up a new system to translate it.
Please remark that's not officially supported by the ToDoList developers, but I used it to translate TDL to Italian and I find it so useful that I think any translators should use it.

If you are interested in giving it a try, here's what you can do:
1. [create a free account](https://www.transifex.com/signup/) on the Transifex (it's an online collaborative platform used by many small and big organizations to translate)
2. Go to the [ToDoList](https://www.transifex.com/mlocati/todolist/) project on Transifex and click the green `Join team` button
3. Once you've done it, I'll accept your request and you'll be able to start translating ToDoList in a much easier way.
4. When you finished translating on Transifex, please [drop me a message](https://www.transifex.com/user/messages/compose/mlocati/): I'll create a pull request on GitHub with your translations (if you prefer I can explain you how to do this step, but it's a bit techy)

**Pull request closed without merging**
