### PR TITLE
Update Italian translations

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by mlocati** [comment]
Fast! Thank you!!

**Comment by Pierre-de-la-Verre** [comment]
```
           > Fast! Thank you!!
```

Online .... ;-)

Thank you for translation.

**Comment by Pierre-de-la-Verre** [comment]
Hi Michele
the Dutch translator asked me for a simple instruction how to use Github for "Translators for Todolist". Me, I got rights from Dan and use Github on a very low level, this is why I can not describe how to create a pull-requests" and so on  ..

Do you have the time to write an instruction for it?

Thanks and regards

Pierre

**Comment by mlocati** [comment]
It's very easy.
You first need a github account (you can create it here: https://github.com/join ).
Then you have to locate the file you want to change (for instance https://github.com/abstractspoon/ToDoList_Resources/blob/master/Translations/Nederlands%20(Belgium).csv ).
Then you can click the crayon icon (it's upper right), change the file as you want and follow the shown instructions.

I follow a completely different approach (local clone, fetch translations from Transifex, convert them from gettext to csv, create a new local branch, commit the translation file changes; push this branch to my github fork and finally create a pull request... I think that what I described above is much easier for a git newbie :wink: )

**Comment by Pierre-de-la-Verre** [comment]
Thanks - he just uploaded the first data ...

**Pull request merged**
