### PR TITLE
Add missing strings to YourLanguage.csv

### PR DESCRIPTION
**Pull request by mlocati**

### CODE REVIEW

**Comment by mlocati** [comment]
PS for those using my [Transifex project](https://www.transifex.com/mlocati/todolist/): you'll see these new strings automatically as to be translated if and once this PR gets accepted :wink:

**Comment by Pierre-de-la-Verre** [comment]
Hi Michele
I will assign this PR to Dan, because I see some (small) problems:

a) TDL does not care about the context (see your answer to me this morning). If you have "Bold .. text" and "bold ... label.123" you only need to translate the first string if they have the same context in translation. Only if they have different meaning, then the translator can(!) use different translations.
b) There are always some strings which are created erratic (they belong to the internal development environment) and it is correct that they are not in YourLanguage.csv. The greatest part of the added lines at the end of the file are strings of this kind.

Thanks and regards

Peter

**Comment by mlocati** [comment]
Accordingly to what I understand (but I might be wrong), TDL doesn't use the context if there's no translation for it.

For instance, if we have a translation file with

``` csv
"Bold" "X" "combobox.1"
"Bold" "Y" "combobox.2"
"Bold" "" "combobox.3"
```
- If we need to translate "Bold" for "combobox.1" TDL uses "X"
- If we need to translate "Bold" for "combobox.2" TDL uses "Y"
- If we need to translate "Bold" for "combobox.3" TDL uses "X" (the first translation of "Bold" without taking care of the context because "Bold" for "combobox.3" is not translated

And that's correct.
For instance, in a menu item we'd use "&X" (so that users may press the key X to choose that item), but in a listbox we shouldn't have this X.

And that's the reason why I'm suggesting this PR: I saw that `"List View"   ""  "checklistbox.1413"` was missing. That leads to this problem:

Sub-menu with access key:
image

Listbox in the preferences:
image

The "Vista a elenco" in the listbox contains the `&` that's used in the menu item, but in this case we shouldn't have it. So, for the same text we'd need two different translations.
That's why I'd need to add the missing
`"List View"    "Vista a elenco"    "checklistbox.1413"`
otherwise TDL uses
`"List View"    "Vista a &elenco"   "menu.34355"`

**Comment by abstractspoon** [comment]
Hi Michele

Where did you find the 'extra' strings?

**Comment by mlocati** [comment]
Hi Dan!
1. I created an empty csv file in the language resources directory.
2. I checked the "add to dictionary" checkbox  (I don't remember exactly its label - I'm not in front of a PC - it's the checkbox in the settings dialog right after the language selection).
3. In the language field I've chosen the name of the empty CSV file.
4. I played randomly with TDL, opening dialogs and so on.
5. I added to YourLanguage.csv the strings that were in that new language file but not in YourLanguage.csv

**Comment by mlocati** [comment]
@abstractspoon Any news about this PR?

**Comment by Pierre-de-la-Verre** [comment]
Hi Dan
please take a look at this topic.

**Comment by abstractspoon** [comment]
I'm happy with this once the 'debug' strings have been removed.

**Comment by mlocati** [comment]
Sorry Dan, I don't understand... What are the debug strings you are referring to?

**Comment by abstractspoon** [comment]
Hi Michel,

Peter knows, so I'll leave it to him to explain.

**Comment by Pierre-de-la-Verre** [comment]
Some strings of the last ones are not needed, because they are from development. I will merge this PR, but I will remove the unneeded strings in the main file.

**Pull request merged**
