### PR TITLE
Update Hebrew (Israel).csv

### PR DESCRIPTION
**Pull request by liorshin**

### CODE REVIEW

**Comment by Pierre-de-la-Verre** [comment]
Hi Lior

you should be able to download it via "right mouseclick on button RAW - Save target as ..."
github_download

**Comment by liorshin** [comment]
Hi

can you point me to the screen / menus which is affected from the lines you
addressed me

tnx

Lior

**Comment by Pierre-de-la-Verre** [comment]
Hi Lior
in this special case - where everything is a parameter and nothing is a text - I suppose that you can use exactly the same code as it is used in English.

When you are looking for the place where a special string is used it is better to ask Dan; he knows it. I have to search and to search ....

**Comment by Pierre-de-la-Verre** [comment]
Hi Lior
what's the current state with the language file? is it locally checked on your PC and ready to be merge to the main file?

Regards

Peter

**Comment by liorshin** [comment]
Hi

I didnt manage to find the screens which could be affected from the lines
you had adressed me in the csv file....
beside that it should be ok (i checked it ans sent the temp file to a
friend for checking)
Lior

**Comment by Pierre-de-la-Verre** [comment]
Hi lior

please consider the current discussion here: "new formatted strings"
http://www.codeproject.com/Messages/5106273/Modified-strings.aspx

There are also the strings you are looking for.

Edit:
Please check if the tooltip, created by the new strings, makes a well formatted table - use more or less \t or longer / shorter words:
tdl_tooltip_german

**Comment by Pierre-de-la-Verre** [comment]
Do you have a flag of Israel (GIF file) which can be added to the other flags?

**Comment by liorshin** [comment]
what is the pixel limit?

**Comment by Pierre-de-la-Verre** [comment]
All the others have 16x11

Peter

Von: liorshin [mailto:notifications@github.com] 
Gesendet: Mittwoch, 12. August 2015 14:16
An: abstractspoon/ToDoList_Resources
Cc: Peter Glasl
Betreff: Re: [ToDoList_Resources] Update Hebrew (Israel).csv (#17)

what is the pixel limit?

**Comment by liorshin** [comment]
attached pleas find the flag pic file

i'll try to finishe the csv checks asap

tnx

lior

**Comment by Pierre-de-la-Verre** [comment]
Where is the flag???

Please send it with mail to Dan or to me: nojunk217 x hotmail x com

**Comment by Pierre-de-la-Verre** [comment]
Solved for TDL 7.0 via E-Mail

**Comment by mlocati** [comment]
Hi @liorshin 

If you're still interested in translating ToDoList, I just set up a new system to translate it.
Please remark that's not officially supported by the ToDoList developers, but I used it to translate TDL to Italian and I find it so useful that I think any translators should use it.

If you are interested in giving it a try, here's what you can do:
1. [create a free account](https://www.transifex.com/signup/) on the Transifex (it's an online collaborative platform used by many small and big organizations to translate)
2. Go to the [ToDoList](https://www.transifex.com/mlocati/todolist/) project on Transifex and click the green `Join team` button
3. Once you've done it, I'll accept your request and you'll be able to start translating ToDoList in a much easier way.
4. When you finished translating on Transifex, please [drop me a message](https://www.transifex.com/user/messages/compose/mlocati/): I'll create a pull request on GitHub with your translations (if you prefer I can explain you how to do this step, but it's a bit techy)

**Pull request closed without merging**
